
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author johnrafaelrondilla
 */
public class deleteUserForm extends javax.swing.JFrame {

    /**
     * Creates new form deleteUserForm
     */
    public deleteUserForm() {
        initComponents();
        populateTable();
        
        btnDel.setVisible(false);
        btnClear.setVisible(false);
        
        txtUser.setEnabled(false);
        txtPass.setEnabled(false);
        lblAcct.setText("");
        txtUser.setBackground(new Color(0,0,0,0));
        txtPass.setBackground(new Color(0,0,0,0));
        lblAcct.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAcct = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeleteUser = new javax.swing.JTable();
        buttonsPanel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        clearDisabled = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        clear = new javax.swing.JLabel();
        deleteDisabled = new javax.swing.JLabel();
        btnDel = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        acctDisabled = new javax.swing.JLabel();
        passDisabled = new javax.swing.JLabel();
        userDisabled = new javax.swing.JLabel();
        userEnabled = new javax.swing.JLabel();
        acctEnabled = new javax.swing.JLabel();
        passEnabled = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAcct.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblAcct.setText("lblAcct");
        getContentPane().add(lblAcct, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, 30));

        tblDeleteUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Password", "Access Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDeleteUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDeleteUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDeleteUser);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 730, 330));

        buttonsPanel.setOpaque(false);
        buttonsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CANCEL-hover.png"))); // NOI18N
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });
        buttonsPanel.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CANCEL.png"))); // NOI18N
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
        });
        buttonsPanel.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        clearDisabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deleteUserForm/CLEAR-DIS.png"))); // NOI18N
        clearDisabled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearDisabledMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearDisabledMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearDisabledMouseEntered(evt);
            }
        });
        buttonsPanel.add(clearDisabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CLEAR-hover.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });
        buttonsPanel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CLEAR.png"))); // NOI18N
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
        });
        buttonsPanel.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        deleteDisabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deleteUserForm/DEL-DIS.png"))); // NOI18N
        deleteDisabled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteDisabledMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteDisabledMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteDisabledMouseExited(evt);
            }
        });
        buttonsPanel.add(deleteDisabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deleteUserForm/del-hov.png"))); // NOI18N
        btnDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDelMouseExited(evt);
            }
        });
        buttonsPanel.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deleteUserForm/DEL.png"))); // NOI18N
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
        });
        buttonsPanel.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(buttonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 280, 50));

        txtPass.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        txtPass.setToolTipText("enter password");
        txtPass.setBorder(null);
        txtPass.setEnabled(false);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 170, 30));

        txtUser.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        txtUser.setToolTipText("enter last name");
        txtUser.setBorder(null);
        txtUser.setEnabled(false);
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 170, 30));

        acctDisabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/acctType-disabled.png"))); // NOI18N
        getContentPane().add(acctDisabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        passDisabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/pass-disabled.png"))); // NOI18N
        getContentPane().add(passDisabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        userDisabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/user-disabled.png"))); // NOI18N
        getContentPane().add(userDisabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        userEnabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/user-enabled.png"))); // NOI18N
        getContentPane().add(userEnabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        acctEnabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/acctType-enabled.png"))); // NOI18N
        getContentPane().add(acctEnabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        passEnabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/pass-enabled.png"))); // NOI18N
        getContentPane().add(passEnabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deleteUserForm/DELETE USER.png"))); // NOI18N
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/Layer 1.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        mainForm m = new mainForm();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        // TODO add your handling code here:
        btnCancel.setVisible(false);
    }//GEN-LAST:event_btnCancelMouseExited

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseExited

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        // TODO add your handling code here:
        btnCancel.setVisible(true);
    }//GEN-LAST:event_cancelMouseEntered

    private void clearDisabledMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearDisabledMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_clearDisabledMouseExited

    private void clearDisabledMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearDisabledMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_clearDisabledMouseEntered

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        
        txtUser.setText("");
        txtPass.setText("");
        lblAcct.setText("");
        
        userDisabled.setVisible(true);
        passDisabled.setVisible(true);
        acctDisabled.setVisible(true);
        deleteDisabled.setVisible(true);
        clearDisabled.setVisible(true);
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        // TODO add your handling code here:
        btnClear.setVisible(false);
    }//GEN-LAST:event_btnClearMouseExited

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_clearMouseExited

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        // TODO add your handling code here:
        btnClear.setVisible(true);
    }//GEN-LAST:event_clearMouseEntered

    private void deleteDisabledMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteDisabledMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteDisabledMouseExited

    private void deleteDisabledMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteDisabledMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteDisabledMouseEntered

    private void btnDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelMouseClicked

        try
        {
            /*Class.forName("org.apache.derby.jdbc.ClientDriver");
            String fidelString = "jdbc:derby://localhost:1527/UserLogin";
            Connection fidelcon = DriverManager.getConnection(fidelString, "login", "login");
            Statement fidelstmt = fidelcon.createStatement();*/
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
            Connection con = DriverManager.getConnection(drive, "", "");
            Statement stmt = con.createStatement();
            
            String insertsql = "delete from users where uname='"+txtUser.getText()+"'";
            String insertsql1 = "delete from history where uname='"+txtUser.getText()+"'";
            stmt.execute(insertsql1);
            stmt.execute(insertsql);
            stmt.close();
            con.close();
            
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, "Account deleted.");
            
            populateTable();
            
            txtUser.setText("");
            txtPass.setText("");
            lblAcct.setText("");
            
            deleteDisabled.setVisible(true);
            clearDisabled.setVisible(true);
            
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
    }//GEN-LAST:event_btnDelMouseClicked

    private void btnDelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelMouseExited
        // TODO add your handling code here:
        btnDel.setVisible(false);
    }//GEN-LAST:event_btnDelMouseExited

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseExited

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        // TODO add your handling code here:
        btnDel.setVisible(true);
    }//GEN-LAST:event_deleteMouseEntered

    private void tblDeleteUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDeleteUserMouseClicked
        // TODO add your handling code here:
        
        deleteDisabled.setVisible(false);
        clearDisabled.setVisible(false);
        
        int row = tblDeleteUser.getSelectedRow();
        String username = (tblDeleteUser.getModel().getValueAt(row, 0).toString());
        try
        {
            /*Class.forName("org.apache.derby.jdbc.ClientDriver");
            String fidelString = "jdbc:derby://localhost:1527/UserLogin";
            Connection fidelcon = DriverManager.getConnection(fidelString, "login", "login");
            Statement fidelstmt = fidelcon.createStatement();
            */
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
            Connection con = DriverManager.getConnection(drive, "", "");
            Statement stmt = con.createStatement();
            
            String query = "select * from users where uname='"+username+"'";
            ResultSet result = stmt.executeQuery(query);
            
            if(result.next())
            {
                String field1 = result.getString("uname");
                txtUser.setText(field1);
                String field2 = result.getString("pword");
                txtPass.setText(field2);
                String field3 = result.getString("access_type");
                lblAcct.setText(field3);
            }
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
    }//GEN-LAST:event_tblDeleteUserMouseClicked

    private void clearDisabledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearDisabledMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clearDisabledMouseClicked

    private void deleteDisabledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteDisabledMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteDisabledMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleteUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleteUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleteUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleteUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleteUserForm().setVisible(true);
            }
        });
    }
    
    public void populateTable()
    {
        try
        {
            /*Class.forName("org.apache.derby.jdbc.ClientDriver");
            String fidelString = "jdbc:derby://localhost:1527/UserLogin";
            Connection fidelcon = DriverManager.getConnection(fidelString, "login", "login");
            Statement fidelstmt = fidelcon.createStatement();*/
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
            Connection con = DriverManager.getConnection(drive, "", "");
            Statement stmt = con.createStatement();
            
            ResultSet record;
            record = stmt.executeQuery("select uname as Username, access_type as Access from users");
            tblDeleteUser.setModel(DbUtils.resultSetToTableModel(record));
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acctDisabled;
    private javax.swing.JLabel acctEnabled;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnDel;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel clear;
    private javax.swing.JLabel clearDisabled;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel deleteDisabled;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAcct;
    private javax.swing.JLabel passDisabled;
    private javax.swing.JLabel passEnabled;
    private javax.swing.JTable tblDeleteUser;
    private javax.swing.JLabel title;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel userDisabled;
    private javax.swing.JLabel userEnabled;
    // End of variables declaration//GEN-END:variables
}
