
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author johnrafaelrondilla
 */
public class loginHistoryForm extends javax.swing.JFrame {

    /**
     * Creates new form loginHistoryForm
     */
    
    public void populateTable()
    {
        try
        {
            /*Class.forName("org.apache.derby.jdbc.ClientDriver");
            String fidelString = "jdbc:derby://localhost:1527/UserLogin";
            Connection fidelcon = DriverManager.getConnection(fidelString, "login", "login");
            Statement fidelstmt = fidelcon.createStatement();*/
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
            Connection con = DriverManager.getConnection(drive, "", "");
            Statement stmt = con.createStatement();
            
            ResultSet record;
            record = stmt.executeQuery("select uname as Username, date_ as Date, time_ as Time from history  order by date_ desc");
            tblLoghis.setModel(DbUtils.resultSetToTableModel(record));
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
    }
    
    public loginHistoryForm() {
        initComponents();
        
        btnSubmit.setVisible(false);
        btnClear.setVisible(false);
        btnCancel.setVisible(false);
        
        ckdDate.setVisible(false);
        ckdUser.setVisible(false);
        
        txtSearchUser.setBackground(new Color(0,0,0,0));
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        form = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        clear = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JLabel();
        submit = new javax.swing.JLabel();
        loghisPane = new javax.swing.JScrollPane();
        tblLoghis = new javax.swing.JTable();
        txtToDate = new javax.swing.JTextField();
        txtFromDate = new javax.swing.JTextField();
        txtSearchUser = new javax.swing.JTextField();
        fromDate1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fromDate = new javax.swing.JLabel();
        srchBox = new javax.swing.JLabel();
        ckdUser = new javax.swing.JLabel();
        btnUser = new javax.swing.JLabel();
        ckdDate = new javax.swing.JLabel();
        btnDate = new javax.swing.JLabel();
        srchby = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        form.setMaximumSize(new java.awt.Dimension(800, 600));
        form.setMinimumSize(new java.awt.Dimension(800, 600));
        form.setOpaque(false);
        form.setPreferredSize(new java.awt.Dimension(800, 600));
        form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonsPanel.setOpaque(false);
        buttonsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CANCEL-hover.png"))); // NOI18N
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });
        buttonsPanel.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CANCEL.png"))); // NOI18N
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
        });
        buttonsPanel.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CLEAR-hover.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });
        buttonsPanel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CLEAR.png"))); // NOI18N
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
        });
        buttonsPanel.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/buttons/SEARCH-HOV.png"))); // NOI18N
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubmitMouseExited(evt);
            }
        });
        buttonsPanel.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/buttons/SEARCH.png"))); // NOI18N
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitMouseEntered(evt);
            }
        });
        buttonsPanel.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        form.add(buttonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 280, 50));

        loghisPane.setBorder(null);
        loghisPane.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N

        tblLoghis.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        tblLoghis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "User", "Date", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoghis.setEnabled(false);
        tblLoghis.setOpaque(false);
        loghisPane.setViewportView(tblLoghis);

        form.add(loghisPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 750, 270));

        txtToDate.setFont(new java.awt.Font("Helvetica", 2, 14)); // NOI18N
        txtToDate.setText("yyyy-mm-dd");
        txtToDate.setBorder(null);
        txtToDate.setEnabled(false);
        txtToDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtToDateFocusGained(evt);
            }
        });
        form.add(txtToDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 120, 30));

        txtFromDate.setFont(new java.awt.Font("Helvetica", 2, 14)); // NOI18N
        txtFromDate.setText("yyyy-mm-dd");
        txtFromDate.setBorder(null);
        txtFromDate.setEnabled(false);
        txtFromDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFromDateFocusGained(evt);
            }
        });
        form.add(txtFromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 120, 30));

        txtSearchUser.setFont(new java.awt.Font("Helvetica", 2, 14)); // NOI18N
        txtSearchUser.setText("enter username...");
        txtSearchUser.setBorder(null);
        txtSearchUser.setEnabled(false);
        txtSearchUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchUserFocusGained(evt);
            }
        });
        form.add(txtSearchUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 210, 30));

        fromDate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/box.png"))); // NOI18N
        form.add(fromDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("from:");
        form.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, 30));

        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("to:");
        form.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, 30));

        fromDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/box.png"))); // NOI18N
        form.add(fromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        srchBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/box2.png"))); // NOI18N
        form.add(srchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 400, 50));

        ckdUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/ckdUser.png"))); // NOI18N
        ckdUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckdUserMouseClicked(evt);
            }
        });
        form.add(ckdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 50));

        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/btnUser.png"))); // NOI18N
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserMouseClicked(evt);
            }
        });
        form.add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 50));

        ckdDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/ckdDate.png"))); // NOI18N
        ckdDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckdDateMouseClicked(evt);
            }
        });
        form.add(ckdDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 50));

        btnDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/btnDate.png"))); // NOI18N
        btnDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDateMouseClicked(evt);
            }
        });
        form.add(btnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 50));

        srchby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/Search By_.png"))); // NOI18N
        form.add(srchby, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 50));

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/LOGIN HISTORY.png"))); // NOI18N
        form.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 60));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/Layer 1.png"))); // NOI18N
        form.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(form, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        mainForm m = new mainForm();
        m.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        // TODO add your handling code here:
        btnCancel.setVisible(false);
    }//GEN-LAST:event_btnCancelMouseExited

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseExited

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        // TODO add your handling code here:
        btnCancel.setVisible(true);
    }//GEN-LAST:event_cancelMouseEntered

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        ckdDate.setVisible(false);
        ckdUser.setVisible(false);
        txtFromDate.setEnabled(false);
        txtToDate.setEnabled(false);
        txtSearchUser.setEnabled(false);
        txtFromDate.setText("yyyy-mm-dd");
        txtToDate.setText("yyyy-mm-dd");
        txtSearchUser.setText("enter username...");
        txtFromDate.requestFocus();
        populateTable();
        
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        // TODO add your handling code here:
        btnClear.setVisible(false);
    }//GEN-LAST:event_btnClearMouseExited

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_clearMouseExited

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        // TODO add your handling code here:
        btnClear.setVisible(true);
    }//GEN-LAST:event_clearMouseEntered

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        // TODO add your handling code here:
        
        if(ckdUser.isVisible())
        {
            try
            {
                Class.forName("org.apache.derby.jdbc.ClientDriver");
                String fidelString = "jdbc:derby://localhost:1527/UserLogin";
                Connection fidelcon = DriverManager.getConnection(fidelString, "login", "login");
                Statement fidelstmt = fidelcon.createStatement();
                ResultSet fidelrecord;
                fidelrecord = fidelstmt.executeQuery("select uname as Username, date_ as Date, time_ as Time from history where uname like '%"+txtSearchUser.getText()+"%'");
                tblLoghis.setModel(DbUtils.resultSetToTableModel(fidelrecord));
                fidelstmt.close();
                fidelcon.close();
            }
            catch(Exception e)
            {
                JFrame frame = new JFrame();
                frame.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(frame, e.getMessage());
            }
        }
        
        if(ckdDate.isVisible())
        {
            try
            {
                Class.forName("org.apache.derby.jdbc.ClientDriver");
                String fidelString = "jdbc:derby://localhost:1527/UserLogin";
                Connection fidelcon = DriverManager.getConnection(fidelString, "login", "login");
                Statement fidelstmt = fidelcon.createStatement();
                ResultSet fidelrecord;
                fidelrecord = fidelstmt.executeQuery("select uname as Username, date_ as Date, time_ as Time from history where date_ between '"+txtFromDate.getText()+"' and '"+txtToDate.getText()+"'");
                tblLoghis.setModel(DbUtils.resultSetToTableModel(fidelrecord));
                fidelstmt.close();
                fidelcon.close();
            }
            catch(Exception e)
            {
                JFrame frame = new JFrame();
                frame.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(frame, e.getMessage());
            }
        }
        

    }//GEN-LAST:event_btnSubmitMouseClicked

    private void btnSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseExited
        // TODO add your handling code here:
        btnSubmit.setVisible(false);
    }//GEN-LAST:event_btnSubmitMouseExited

    private void submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_submitMouseExited

    private void submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseEntered
        // TODO add your handling code here:
        btnSubmit.setVisible(true);
    }//GEN-LAST:event_submitMouseEntered

    private void btnDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDateMouseClicked
        // TODO add your handling code here:
        ckdDate.setVisible(true);
        ckdUser.setVisible(false);
        txtFromDate.setEnabled(true);
        
        txtToDate.setEnabled(true);
        
        
        txtSearchUser.setEnabled(false);
        txtSearchUser.setText("enter username...");
    }//GEN-LAST:event_btnDateMouseClicked

    private void btnUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseClicked
        // TODO add your handling code here:
        ckdDate.setVisible(false);
        ckdUser.setVisible(true);
        txtSearchUser.setEnabled(true);
        
        
        txtFromDate.setEnabled(false);
        txtToDate.setEnabled(false);
        txtToDate.setText("yyyy-mm-dd");
        txtFromDate.setText("yyyy-mm-dd");
    }//GEN-LAST:event_btnUserMouseClicked

    private void ckdDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckdDateMouseClicked
        // TODO add your handling code here:
        ckdDate.setVisible(false);
        txtFromDate.setEnabled(false);
        txtToDate.setEnabled(false);
        txtToDate.setText("yyyy-mm-dd");
        txtFromDate.setText("yyyy-mm-dd");
    }//GEN-LAST:event_ckdDateMouseClicked

    private void ckdUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckdUserMouseClicked
        // TODO add your handling code here:
        ckdUser.setVisible(false);
        txtSearchUser.setEnabled(false);
        txtSearchUser.setText("enter username...");
    }//GEN-LAST:event_ckdUserMouseClicked

    private void txtFromDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFromDateFocusGained
        // TODO add your handling code here:
        txtFromDate.setText("");
    }//GEN-LAST:event_txtFromDateFocusGained

    private void txtToDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtToDateFocusGained
        // TODO add your handling code here:
        txtToDate.setText("");
    }//GEN-LAST:event_txtToDateFocusGained

    private void txtSearchUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchUserFocusGained
        // TODO add your handling code here:
        txtSearchUser.setText("");
    }//GEN-LAST:event_txtSearchUserFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginHistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginHistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginHistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginHistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginHistoryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnDate;
    private javax.swing.JLabel btnSubmit;
    private javax.swing.JLabel btnUser;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel ckdDate;
    private javax.swing.JLabel ckdUser;
    private javax.swing.JLabel clear;
    private javax.swing.JPanel form;
    private javax.swing.JLabel fromDate;
    private javax.swing.JLabel fromDate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane loghisPane;
    private javax.swing.JLabel srchBox;
    private javax.swing.JLabel srchby;
    private javax.swing.JLabel submit;
    private javax.swing.JTable tblLoghis;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtFromDate;
    private javax.swing.JTextField txtSearchUser;
    private javax.swing.JTextField txtToDate;
    // End of variables declaration//GEN-END:variables
}
