
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
//import com.mindfusion.scheduling.Calendar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author johnrafaelrondilla
 */
public class mainForm extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    public mainForm() {
        initComponents();
        
        hMenu.setVisible(false);
        hUser.setVisible(false);
        hRecord.setVisible(false);
        hTrans.setVisible(false);

        
        menuPanel.setVisible(false);
        userPanel.setVisible(false);
        recordPanel.setVisible(false);
        transPanel.setVisible(false);
        recordPanel.setVisible(false);
        

        btnLogout.setVisible(false);
        btnLoghis.setVisible(false);
        btnNewUser.setVisible(false);
        btnUpUser.setVisible(false);
        //btnDelUser.setVisible(false);

        btnnewP.setVisible(false);
        btnupP.setVisible(false);
        btnsrchP.setVisible(false);
        btntranshis.setVisible(false);
        btnTally.setVisible(false);
        
        
        
        showDate();
        showTime();
    }
    
    void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("MM-dd-yyyy");
        txtDate.setText(s.format(d));
    }
    
    void showTime(){
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                txtTime.setText(s.format(d)); 
            }
        }).start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTally2 = new javax.swing.JButton();
        txtTime = new javax.swing.JLabel();
        today1 = new javax.swing.JLabel();
        today = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        transPanel = new javax.swing.JPanel();
        btnTally = new javax.swing.JButton();
        btnCalendar = new javax.swing.JButton();
        btntranshis = new javax.swing.JButton();
        transHis = new javax.swing.JButton();
        pTrans = new javax.swing.JLabel();
        recordPanel = new javax.swing.JPanel();
        btnsrchP = new javax.swing.JButton();
        srchP = new javax.swing.JButton();
        btnupP = new javax.swing.JButton();
        upP = new javax.swing.JButton();
        btnnewP = new javax.swing.JButton();
        newP = new javax.swing.JButton();
        pRecord = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        btnUpUser = new javax.swing.JButton();
        upUser = new javax.swing.JButton();
        btnNewUser = new javax.swing.JButton();
        newUser = new javax.swing.JButton();
        pUsers = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        btnLoghis = new javax.swing.JButton();
        loghis = new javax.swing.JButton();
        pMenu = new javax.swing.JLabel();
        hTrans = new javax.swing.JButton();
        trans = new javax.swing.JButton();
        hRecord = new javax.swing.JButton();
        record = new javax.swing.JButton();
        hUser = new javax.swing.JButton();
        user = new javax.swing.JButton();
        hMenu = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        bg = new javax.swing.JLabel();
        menu2 = new javax.swing.JLabel();

        btnTally2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        btnTally2.setText("Services");
        btnTally2.setBorderPainted(false);
        btnTally2.setContentAreaFilled(false);
        btnTally2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTally2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTally2MouseExited(evt);
            }
        });
        btnTally2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTally2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTime.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        txtTime.setForeground(new java.awt.Color(255, 255, 255));
        txtTime.setText("time");
        getContentPane().add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 560, 50));

        today1.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        today1.setForeground(new java.awt.Color(255, 255, 255));
        today1.setText("The time is:");
        getContentPane().add(today1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 240, 50));

        today.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        today.setForeground(new java.awt.Color(255, 255, 255));
        today.setText("Today is:");
        getContentPane().add(today, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 110, 50));

        txtDate.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        txtDate.setForeground(new java.awt.Color(255, 255, 255));
        txtDate.setText("date");
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 310, 50));

        transPanel.setMaximumSize(new java.awt.Dimension(250, 198));
        transPanel.setMinimumSize(new java.awt.Dimension(250, 198));
        transPanel.setOpaque(false);
        transPanel.setPreferredSize(new java.awt.Dimension(250, 198));
        transPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTally.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btnTally.setText("Services");
        btnTally.setBorderPainted(false);
        btnTally.setContentAreaFilled(false);
        btnTally.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTallyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTallyMouseExited(evt);
            }
        });
        btnTally.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTallyActionPerformed(evt);
            }
        });
        transPanel.add(btnTally, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 350, 50));

        btnCalendar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCalendar.setText("Appoint Schedule");
        btnCalendar.setBorderPainted(false);
        btnCalendar.setContentAreaFilled(false);
        btnCalendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCalendarMouseEntered(evt);
            }
        });
        btnCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarActionPerformed(evt);
            }
        });
        transPanel.add(btnCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 330, 50));

        btntranshis.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btntranshis.setText("Transaction History");
        btntranshis.setBorderPainted(false);
        btntranshis.setContentAreaFilled(false);
        btntranshis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btntranshisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btntranshisMouseExited(evt);
            }
        });
        btntranshis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntranshisActionPerformed(evt);
            }
        });
        transPanel.add(btntranshis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 340, 60));

        transHis.setBorderPainted(false);
        transHis.setContentAreaFilled(false);
        transHis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transHisMouseEntered(evt);
            }
        });
        transHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transHisActionPerformed(evt);
            }
        });
        transPanel.add(transHis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 330, 70));

        pTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainFrame/trans-options/TRI.png"))); // NOI18N
        pTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pTransMouseEntered(evt);
            }
        });
        transPanel.add(pTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 170));

        getContentPane().add(transPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 430, 200));

        recordPanel.setMaximumSize(new java.awt.Dimension(250, 198));
        recordPanel.setMinimumSize(new java.awt.Dimension(250, 198));
        recordPanel.setOpaque(false);
        recordPanel.setPreferredSize(new java.awt.Dimension(250, 198));
        recordPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsrchP.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnsrchP.setText("Search Patient");
        btnsrchP.setToolTipText("");
        btnsrchP.setBorderPainted(false);
        btnsrchP.setContentAreaFilled(false);
        btnsrchP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsrchPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsrchPMouseExited(evt);
            }
        });
        btnsrchP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsrchPActionPerformed(evt);
            }
        });
        recordPanel.add(btnsrchP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 60));

        srchP.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        srchP.setBorderPainted(false);
        srchP.setContentAreaFilled(false);
        srchP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                srchPMouseEntered(evt);
            }
        });
        srchP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchPActionPerformed(evt);
            }
        });
        recordPanel.add(srchP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 210, 70));

        btnupP.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnupP.setText("Update Patient");
        btnupP.setBorderPainted(false);
        btnupP.setContentAreaFilled(false);
        btnupP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnupPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnupPMouseExited(evt);
            }
        });
        btnupP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupPActionPerformed(evt);
            }
        });
        recordPanel.add(btnupP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 280, 70));

        upP.setBorderPainted(false);
        upP.setContentAreaFilled(false);
        upP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                upPMouseEntered(evt);
            }
        });
        upP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upPActionPerformed(evt);
            }
        });
        recordPanel.add(upP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 210, 70));

        btnnewP.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnnewP.setText("New Patient");
        btnnewP.setBorderPainted(false);
        btnnewP.setContentAreaFilled(false);
        btnnewP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnnewPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnnewPMouseExited(evt);
            }
        });
        btnnewP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewPActionPerformed(evt);
            }
        });
        recordPanel.add(btnnewP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, 80));

        newP.setBorderPainted(false);
        newP.setContentAreaFilled(false);
        newP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newPMouseEntered(evt);
            }
        });
        newP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPActionPerformed(evt);
            }
        });
        recordPanel.add(newP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 190, 70));

        pRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainFrame/records-options/TRI.png"))); // NOI18N
        pRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pRecordMouseEntered(evt);
            }
        });
        recordPanel.add(pRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, -1));

        getContentPane().add(recordPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 320, 200));

        userPanel.setMaximumSize(new java.awt.Dimension(250, 198));
        userPanel.setMinimumSize(new java.awt.Dimension(250, 198));
        userPanel.setOpaque(false);
        userPanel.setPreferredSize(new java.awt.Dimension(250, 198));
        userPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpUser.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnUpUser.setText("Update User");
        btnUpUser.setBorderPainted(false);
        btnUpUser.setContentAreaFilled(false);
        btnUpUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpUserMouseExited(evt);
            }
        });
        btnUpUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpUserActionPerformed(evt);
            }
        });
        userPanel.add(btnUpUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 270, -1));

        upUser.setBorderPainted(false);
        upUser.setContentAreaFilled(false);
        upUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                upUserMouseEntered(evt);
            }
        });
        userPanel.add(upUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 70));

        btnNewUser.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnNewUser.setText("New User");
        btnNewUser.setBorderPainted(false);
        btnNewUser.setContentAreaFilled(false);
        btnNewUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewUserMouseExited(evt);
            }
        });
        btnNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewUserActionPerformed(evt);
            }
        });
        userPanel.add(btnNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 270, -1));

        newUser.setBorderPainted(false);
        newUser.setContentAreaFilled(false);
        newUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newUserMouseEntered(evt);
            }
        });
        newUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserActionPerformed(evt);
            }
        });
        userPanel.add(newUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 160, 70));

        pUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainFrame/users-option/TRI-2.png"))); // NOI18N
        pUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pUsersMouseEntered(evt);
            }
        });
        userPanel.add(pUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 250));

        getContentPane().add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 300, 120));

        menuPanel.setOpaque(false);
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        menuPanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 80));

        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
        });
        menuPanel.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 280, 60));

        btnLoghis.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnLoghis.setText("Login History");
        btnLoghis.setBorderPainted(false);
        btnLoghis.setContentAreaFilled(false);
        btnLoghis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoghisMouseExited(evt);
            }
        });
        btnLoghis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoghisActionPerformed(evt);
            }
        });
        menuPanel.add(btnLoghis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 250, 80));

        loghis.setBorderPainted(false);
        loghis.setContentAreaFilled(false);
        loghis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loghisMouseEntered(evt);
            }
        });
        loghis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loghisActionPerformed(evt);
            }
        });
        menuPanel.add(loghis, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 9, 250, 60));

        pMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainFrame/menu-options/TRI.png"))); // NOI18N
        menuPanel.add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 330, 130));

        hTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainFrame/hovers/TRANSACTIONS-hover.png"))); // NOI18N
        hTrans.setBorderPainted(false);
        hTrans.setContentAreaFilled(false);
        hTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hTransMouseExited(evt);
            }
        });
        hTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hTransActionPerformed(evt);
            }
        });
        getContentPane().add(hTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 460, 60));

        trans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainFrame/TRANSACTIONS.png"))); // NOI18N
        trans.setBorderPainted(false);
        trans.setContentAreaFilled(false);
        trans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transMouseEntered(evt);
            }
        });
        trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transActionPerformed(evt);
            }
        });
        getContentPane().add(trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 460, 60));

        hRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainFrame/hovers/RECORDS-HOVER.png"))); // NOI18N
        hRecord.setBorderPainted(false);
        hRecord.setContentAreaFilled(false);
        hRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hRecordMouseExited(evt);
            }
        });
        hRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hRecordActionPerformed(evt);
            }
        });
        getContentPane().add(hRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 460, 60));

        record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainFrame/RECORDS.png"))); // NOI18N
        record.setBorderPainted(false);
        record.setContentAreaFilled(false);
        record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recordMouseEntered(evt);
            }
        });
        record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordActionPerformed(evt);
            }
        });
        getContentPane().add(record, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 460, 60));

        hUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainFrame/hovers/USERS-hover.png"))); // NOI18N
        hUser.setBorderPainted(false);
        hUser.setContentAreaFilled(false);
        hUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hUserMouseExited(evt);
            }
        });
        hUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hUserActionPerformed(evt);
            }
        });
        getContentPane().add(hUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 460, 60));

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainFrame/USERS.png"))); // NOI18N
        user.setBorderPainted(false);
        user.setContentAreaFilled(false);
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userMouseEntered(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 460, 60));

        hMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainFrame/hovers/MENU-hover.png"))); // NOI18N
        hMenu.setBorderPainted(false);
        hMenu.setContentAreaFilled(false);
        hMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hMenuMouseExited(evt);
            }
        });
        hMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hMenuActionPerformed(evt);
            }
        });
        getContentPane().add(hMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 460, 60));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainFrame/MENU.png"))); // NOI18N
        menu.setBorderPainted(false);
        menu.setContentAreaFilled(false);
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
        });
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 460, 60));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainFrame/Layer 1.png"))); // NOI18N
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bgMouseEntered(evt);
            }
        });
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -20, -1, 800));

        menu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainFrame/menu-options/Login.png"))); // NOI18N
        menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu2MouseEntered(evt);
            }
        });
        getContentPane().add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -120, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menu2MouseEntered

    private void bgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseEntered
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_bgMouseEntered

    private void pUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pUsersMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pUsersMouseEntered

    private void bgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseClicked
        // TODO add your handling code here:
        menuPanel.setVisible(false);
        userPanel.setVisible(false);
        userPanel.setVisible(false);
        recordPanel.setVisible(false);
        transPanel.setVisible(false);
    }//GEN-LAST:event_bgMouseClicked

    private void hMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hMenuActionPerformed
        // TODO add your handling code here:
        menuPanel.setVisible(true);
        userPanel.setVisible(false);
        recordPanel.setVisible(false);
        transPanel.setVisible(false);
    }//GEN-LAST:event_hMenuActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        menuPanel.setVisible(true);
        userPanel.setVisible(false);
        recordPanel.setVisible(false);
        transPanel.setVisible(false);
    }//GEN-LAST:event_menuActionPerformed

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
        // TODO add your handling code here:
        hMenu.setVisible(true);
    }//GEN-LAST:event_menuMouseEntered

    private void hMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hMenuMouseExited
        // TODO add your handling code here:
        hMenu.setVisible(false);
    }//GEN-LAST:event_hMenuMouseExited

    private void hUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hUserMouseExited
        // TODO add your handling code here:
        hUser.setVisible(false);
    }//GEN-LAST:event_hUserMouseExited

    private void hUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hUserActionPerformed
        // TODO add your handling code here:
        userPanel.setVisible(true);
        menuPanel.setVisible(false);
        recordPanel.setVisible(false);
        transPanel.setVisible(false);
    }//GEN-LAST:event_hUserActionPerformed

    private void userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseEntered
        // TODO add your handling code here:
        hUser.setVisible(true);
    }//GEN-LAST:event_userMouseEntered

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
        userPanel.setVisible(true);
        menuPanel.setVisible(false);
        recordPanel.setVisible(false);
        transPanel.setVisible(false);
    }//GEN-LAST:event_userActionPerformed

    private void hRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hRecordMouseExited
        // TODO add your handling code here:
        hRecord.setVisible(false);
    }//GEN-LAST:event_hRecordMouseExited

    private void hRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hRecordActionPerformed
        // TODO add your handling code here:
        menuPanel.setVisible(false);
        userPanel.setVisible(false);
        recordPanel.setVisible(true);
        transPanel.setVisible(false);
    }//GEN-LAST:event_hRecordActionPerformed

    private void recordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordMouseEntered
        // TODO add your handling code here:
        hRecord.setVisible(true);
    }//GEN-LAST:event_recordMouseEntered

    private void recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordActionPerformed
        // TODO add your handling code here:
        menuPanel.setVisible(false);
        userPanel.setVisible(false);
        recordPanel.setVisible(true);
        transPanel.setVisible(false);
        
    }//GEN-LAST:event_recordActionPerformed

    private void hTransMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hTransMouseExited
        // TODO add your handling code here:
        hTrans.setVisible(false);
    }//GEN-LAST:event_hTransMouseExited

    private void hTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hTransActionPerformed
        // TODO add your handling code here:
        transPanel.setVisible(true);
        menuPanel.setVisible(false);
        userPanel.setVisible(false);
        recordPanel.setVisible(false);
    }//GEN-LAST:event_hTransActionPerformed

    private void transMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transMouseEntered
        // TODO add your handling code here:
        hTrans.setVisible(true);
    }//GEN-LAST:event_transMouseEntered

    private void transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transActionPerformed
        // TODO add your handling code here:
        transPanel.setVisible(true);
        menuPanel.setVisible(false);
        userPanel.setVisible(false);
        recordPanel.setVisible(false);
    }//GEN-LAST:event_transActionPerformed

    private void loghisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loghisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loghisActionPerformed

    private void loghisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loghisMouseEntered
        // TODO add your handling code here:
        btnLoghis.setVisible(true);
    }//GEN-LAST:event_loghisMouseEntered

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setVisible(true);
    }//GEN-LAST:event_logoutMouseEntered

    private void upUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upUserMouseEntered
        // TODO add your handling code here:
        btnUpUser.setVisible(true);
    }//GEN-LAST:event_upUserMouseEntered

    private void newUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newUserActionPerformed

    private void newUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserMouseEntered
        // TODO add your handling code here:
        btnNewUser.setVisible(true);
    }//GEN-LAST:event_newUserMouseEntered

    private void btnNewUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewUserMouseExited
        // TODO add your handling code here:
        btnNewUser.setVisible(false);
    }//GEN-LAST:event_btnNewUserMouseExited

    private void btnUpUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpUserMouseExited
        // TODO add your handling code here:
        btnUpUser.setVisible(false);
    }//GEN-LAST:event_btnUpUserMouseExited

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setVisible(false);
        
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUserActionPerformed
        // TODO add your handling code here:
        newUserForm n = new newUserForm();
        n.setVisible(true);
        this.setVisible(false);
        
         try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
           String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
           Connection con = DriverManager.getConnection(drive, "", "");
           Statement stmt = con.createStatement();
           
                Calendar cal = Calendar.getInstance();
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");  
                String history = "insert into history(uname, date_, time_,activity) values('"+userLog.ase+"','"+java.time.LocalDate.now()+"', '"+sdf.format(cal.getTime())+"','Added New User')";
                stmt.execute(history);
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
    }//GEN-LAST:event_btnNewUserActionPerformed

    private void btnLoghisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoghisMouseExited
        // TODO add your handling code here:
        btnLoghis.setVisible(false);
    }//GEN-LAST:event_btnLoghisMouseExited

    private void newPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newPMouseEntered
        // TODO add your handling code here:
        btnnewP.setVisible(true);
        btnsrchP.setVisible(false);
    }//GEN-LAST:event_newPMouseEntered

    private void newPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPActionPerformed

    private void pRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pRecordMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pRecordMouseEntered

    private void btnnewPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnewPMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnnewPMouseEntered

    private void btnnewPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewPActionPerformed
        // TODO add your handling code here:
        newPatientForm p = new newPatientForm();
        p.setVisible(true);
        this.setVisible(false);
         try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
           String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
           Connection con = DriverManager.getConnection(drive, "", "");
           Statement stmt = con.createStatement();
           
                Calendar cal = Calendar.getInstance();
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");  
                String history = "insert into history(uname, date_, time_,activity) values('"+userLog.ase+"','"+java.time.LocalDate.now()+"', '"+sdf.format(cal.getTime())+"','Added New Patient')";
                stmt.execute(history);
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
    }//GEN-LAST:event_btnnewPActionPerformed

    private void btnnewPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnewPMouseExited
        // TODO add your handling code here:
        btnnewP.setVisible(false);
    }//GEN-LAST:event_btnnewPMouseExited

    private void btntranshisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntranshisMouseExited
        // TODO add your handling code here:
        btntranshis.setVisible(false);
    }//GEN-LAST:event_btntranshisMouseExited

    private void btntranshisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntranshisMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btntranshisMouseEntered

    private void btntranshisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntranshisActionPerformed
        // TODO add your handling code here:
        transactionHistoryForm t = new transactionHistoryForm();
        t.setVisible(true);
        this.setVisible(false);
        
         try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
           String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
           Connection con = DriverManager.getConnection(drive, "", "");
           Statement stmt = con.createStatement();
           
                Calendar cal = Calendar.getInstance();
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");  
                String history = "insert into history(uname, date_, time_,activity) values('"+userLog.ase+"','"+java.time.LocalDate.now()+"', '"+sdf.format(cal.getTime())+"','Transaction History')";
                stmt.execute(history);
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
    }//GEN-LAST:event_btntranshisActionPerformed

    private void transHisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transHisMouseEntered
        // TODO add your handling code here:
        btntranshis.setVisible(true);
    }//GEN-LAST:event_transHisMouseEntered

    private void transHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transHisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transHisActionPerformed

    private void pTransMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTransMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pTransMouseEntered

    private void upPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upPActionPerformed

    private void upPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upPMouseEntered
        // TODO add your handling code here:
        btnupP.setVisible(true);
        btnsrchP.setVisible(false);
    }//GEN-LAST:event_upPMouseEntered

    private void btnupPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupPActionPerformed
        // TODO add your handling code here:
        updatePatientForm u = new updatePatientForm();
        u.setVisible(true);
        this.setVisible(false);
         try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
           String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
           Connection con = DriverManager.getConnection(drive, "", "");
           Statement stmt = con.createStatement();
           
                Calendar cal = Calendar.getInstance();
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");  
                String history = "insert into history(uname, date_, time_,activity) values('"+userLog.ase+"','"+java.time.LocalDate.now()+"', '"+sdf.format(cal.getTime())+"','Update Patient')";
                stmt.execute(history);
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
    }//GEN-LAST:event_btnupPActionPerformed

    private void btnupPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupPMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnupPMouseEntered

    private void btnupPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupPMouseExited
        // TODO add your handling code here:
        btnupP.setVisible(false);
    }//GEN-LAST:event_btnupPMouseExited

    private void srchPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srchPActionPerformed

    private void srchPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_srchPMouseEntered
        // TODO add your handling code here:
        btnsrchP.setVisible(true);
    }//GEN-LAST:event_srchPMouseEntered

    private void btnsrchPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsrchPActionPerformed
        // TODO add your handling code here:
        searchPatientForm s = new searchPatientForm();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnsrchPActionPerformed

    private void btnsrchPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsrchPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsrchPMouseEntered

    private void btnsrchPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsrchPMouseExited
        // TODO add your handling code here:
        btnsrchP.setVisible(false);
        
    }//GEN-LAST:event_btnsrchPMouseExited

    private void btnTallyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTallyMouseExited
        // TODO add your handling code here:
        btnTally.setVisible(false);
        
    }//GEN-LAST:event_btnTallyMouseExited

    private void btnTallyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTallyMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTallyMouseEntered

    private void btnTallyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTallyActionPerformed
        // TODO add your handling code here:
        //servicesTallyForm s = new servicesTallyForm();
        Services s = new Services();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTallyActionPerformed

    private void btnCalendarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalendarMouseEntered
        // TODO add your handling code here:
        btnTally.setVisible(true);
    }//GEN-LAST:event_btnCalendarMouseEntered

    private void btnCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCalendarActionPerformed

    private void btnLoghisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoghisActionPerformed
        // TODO add your handling code here:
        loginHistoryForm l = new loginHistoryForm();
        l.setVisible(true);
        this.setVisible(false);
        try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
           String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
           Connection con = DriverManager.getConnection(drive, "", "");
           Statement stmt = con.createStatement();
           
                Calendar cal = Calendar.getInstance();
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");  
                String history = "insert into history(uname, date_, time_,activity) values('"+userLog.ase+"','"+java.time.LocalDate.now()+"', '"+sdf.format(cal.getTime())+"','Accessed Login History')";
                stmt.execute(history);
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
        
    }//GEN-LAST:event_btnLoghisActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        loginForm l = new loginForm();
        l.setVisible(true);
        this.setVisible(false);
         try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
           String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
           Connection con = DriverManager.getConnection(drive, "", "");
           Statement stmt = con.createStatement();
           
                Calendar cal = Calendar.getInstance();
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");  
                String history = "insert into history(uname, date_, time_,activity) values('"+userLog.ase+"','"+java.time.LocalDate.now()+"', '"+sdf.format(cal.getTime())+"','Logged Out')";
                stmt.execute(history);
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnUpUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpUserActionPerformed
        // TODO add your handling code here:
        updateUserForm u = new updateUserForm();
        u.setVisible(true);
        this.setVisible(false);
        
         try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
           String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
           Connection con = DriverManager.getConnection(drive, "", "");
           Statement stmt = con.createStatement();
           
                Calendar cal = Calendar.getInstance();
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");  
                String history = "insert into history(uname, date_, time_,activity) values('"+userLog.ase+"','"+java.time.LocalDate.now()+"', '"+sdf.format(cal.getTime())+"','Update User')";
                stmt.execute(history);
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
    }//GEN-LAST:event_btnUpUserActionPerformed

    private void btnTally2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTally2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTally2MouseEntered

    private void btnTally2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTally2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTally2MouseExited

    private void btnTally2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTally2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTally2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnCalendar;
    public javax.swing.JButton btnLoghis;
    public javax.swing.JButton btnLogout;
    public javax.swing.JButton btnNewUser;
    public javax.swing.JButton btnTally;
    public javax.swing.JButton btnTally2;
    public javax.swing.JButton btnUpUser;
    private javax.swing.JButton btnnewP;
    private javax.swing.JButton btnsrchP;
    public javax.swing.JButton btntranshis;
    private javax.swing.JButton btnupP;
    private javax.swing.JButton hMenu;
    private javax.swing.JButton hRecord;
    private javax.swing.JButton hTrans;
    private javax.swing.JButton hUser;
    private javax.swing.JButton loghis;
    private javax.swing.JButton logout;
    private javax.swing.JButton menu;
    private javax.swing.JLabel menu2;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton newP;
    private javax.swing.JButton newUser;
    private javax.swing.JLabel pMenu;
    private javax.swing.JLabel pRecord;
    private javax.swing.JLabel pTrans;
    private javax.swing.JLabel pUsers;
    private javax.swing.JButton record;
    private javax.swing.JPanel recordPanel;
    private javax.swing.JButton srchP;
    private javax.swing.JLabel today;
    private javax.swing.JLabel today1;
    private javax.swing.JButton trans;
    private javax.swing.JButton transHis;
    private javax.swing.JPanel transPanel;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtTime;
    private javax.swing.JButton upP;
    private javax.swing.JButton upUser;
    private javax.swing.JButton user;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
