
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author johnrafaelrondilla
 */
public class newUserForm extends javax.swing.JFrame {

    /**
     * Creates new form newUserForm
     */
    public newUserForm() {
        initComponents();
        
        acctTypePanel.setVisible(false);
        aTypeShow.setText("");
        aType3.setVisible(false);
        aType4.setVisible(false);
        

        txtUser.setBackground(new Color(0,0,0,0));
        txtPass.setBackground(new Color(0,0,0,0));

        
        clk_passvisible.setVisible(false);
        
        userTaken.setVisible(false);
        reqAcct.setVisible(false);
        
        btnSubmit.setVisible(false);
        btnClear.setVisible(false);
        btnCancel.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userTaken = new javax.swing.JLabel();
        reqAcct = new javax.swing.JLabel();
        acctTypePanel = new javax.swing.JPanel();
        aType4 = new javax.swing.JLabel();
        aType3 = new javax.swing.JLabel();
        aType2 = new javax.swing.JLabel();
        aType1 = new javax.swing.JLabel();
        aType0 = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        clear = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JLabel();
        submit = new javax.swing.JLabel();
        clk_passvisible = new javax.swing.JLabel();
        passvisible = new javax.swing.JLabel();
        rec = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        aTypeShow = new javax.swing.JLabel();
        acct = new javax.swing.JLabel();
        form = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(450, 400));
        setMinimumSize(new java.awt.Dimension(450, 400));
        setPreferredSize(new java.awt.Dimension(450, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userTaken.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        userTaken.setForeground(new java.awt.Color(255, 255, 102));
        userTaken.setText("*username taken");
        getContentPane().add(userTaken, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 110, 30));

        reqAcct.setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        reqAcct.setForeground(new java.awt.Color(255, 255, 102));
        reqAcct.setText("*account type required");
        getContentPane().add(reqAcct, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, 30));

        acctTypePanel.setMaximumSize(new java.awt.Dimension(188, 147));
        acctTypePanel.setMinimumSize(new java.awt.Dimension(188, 147));
        acctTypePanel.setOpaque(false);
        acctTypePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aType4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createNewUserForm/accttype/Assistant-hov.png"))); // NOI18N
        aType4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aType4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aType4MouseExited(evt);
            }
        });
        acctTypePanel.add(aType4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        aType3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createNewUserForm/accttype/Dentist-hov.png"))); // NOI18N
        aType3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aType3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aType3MouseExited(evt);
            }
        });
        acctTypePanel.add(aType3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        aType2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createNewUserForm/accttype/Assistant.png"))); // NOI18N
        aType2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aType2MouseEntered(evt);
            }
        });
        acctTypePanel.add(aType2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, -1));

        aType1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createNewUserForm/accttype/Dentist.png"))); // NOI18N
        aType1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aType1MouseEntered(evt);
            }
        });
        acctTypePanel.add(aType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, -1));

        aType0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createNewUserForm/accttype/accttype_click.png"))); // NOI18N
        aType0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aType0MouseClicked(evt);
            }
        });
        acctTypePanel.add(aType0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, -1));

        getContentPane().add(acctTypePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 230, 160));

        buttonsPanel.setOpaque(false);
        buttonsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CANCEL-hover.png"))); // NOI18N
        btnCancel.setToolTipText("cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });
        buttonsPanel.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CANCEL.png"))); // NOI18N
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
        });
        buttonsPanel.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CLEAR-hover.png"))); // NOI18N
        btnClear.setToolTipText("clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });
        buttonsPanel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CLEAR.png"))); // NOI18N
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
        });
        buttonsPanel.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/SUBMIT-hover.png"))); // NOI18N
        btnSubmit.setToolTipText("submit");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubmitMouseExited(evt);
            }
        });
        buttonsPanel.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/SUBMIT.png"))); // NOI18N
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitMouseEntered(evt);
            }
        });
        buttonsPanel.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(buttonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 280, 50));

        clk_passvisible.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clk_passvisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userLogin/pass_v.png"))); // NOI18N
        clk_passvisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clk_passvisibleMouseClicked(evt);
            }
        });
        getContentPane().add(clk_passvisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 40, 30));

        passvisible.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passvisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userLogin/pass_v_c.png"))); // NOI18N
        passvisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passvisibleMouseClicked(evt);
            }
        });
        getContentPane().add(passvisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 40, 30));

        rec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createNewUserForm/Rounded Rectangle 1.png"))); // NOI18N
        getContentPane().add(rec, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 60, -1));

        txtPass.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        txtPass.setToolTipText("enter password");
        txtPass.setBorder(null);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 140, 30));

        txtUser.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        txtUser.setToolTipText("enter username");
        txtUser.setBorder(null);
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 170, 30));

        pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createNewUserForm/userpass/pass.png"))); // NOI18N
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, -1));

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createNewUserForm/userpass/user.png"))); // NOI18N
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        aTypeShow.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        aTypeShow.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aTypeShow.setText("jLabel1");
        getContentPane().add(aTypeShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 120, 30));

        acct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createNewUserForm/accttype/acct.png"))); // NOI18N
        acct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acctMouseClicked(evt);
            }
        });
        getContentPane().add(acct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 70));

        form.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createNewUserForm/formv3.png"))); // NOI18N
        getContentPane().add(form, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void aType1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aType1MouseEntered
        // TODO add your handling code here:
        aType3.setVisible(true);
    }//GEN-LAST:event_aType1MouseEntered

    private void aType2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aType2MouseEntered
        // TODO add your handling code here:
        aType4.setVisible(true);
    }//GEN-LAST:event_aType2MouseEntered

    private void aType3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aType3MouseExited
        // TODO add your handling code here:
        aType3.setVisible(false);
    }//GEN-LAST:event_aType3MouseExited

    private void aType4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aType4MouseExited
        // TODO add your handling code here:
        aType4.setVisible(false);
    }//GEN-LAST:event_aType4MouseExited

    private void aType0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aType0MouseClicked
        // TODO add your handling code here:
        acctTypePanel.setVisible(false);
    }//GEN-LAST:event_aType0MouseClicked

    private void acctMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acctMouseClicked
        // TODO add your handling code here:
        acctTypePanel.setVisible(true);
    }//GEN-LAST:event_acctMouseClicked

    private void aType3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aType3MouseClicked
        // TODO add your handling code here:
        aTypeShow.setText("admin");
        acctTypePanel.setVisible(false);
        
        user.setVisible(true);
        txtUser.setVisible(true);
        
        pass.setVisible(true);
        txtPass.setVisible(true);
        
        
        passvisible.setVisible(true);
        
    }//GEN-LAST:event_aType3MouseClicked

    private void aType4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aType4MouseClicked
        // TODO add your handling code here:
        aTypeShow.setText("user");
        acctTypePanel.setVisible(false);
        
        user.setVisible(true);
        txtUser.setVisible(true);
        
        pass.setVisible(true);
        txtPass.setVisible(true);
        
        
        passvisible.setVisible(true);
        
    }//GEN-LAST:event_aType4MouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        mainForm m = new mainForm();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        // TODO add your handling code here:
        btnCancel.setVisible(false);
    }//GEN-LAST:event_btnCancelMouseExited

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_cancelMouseExited

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        // TODO add your handling code here:
        btnCancel.setVisible(true);
    }//GEN-LAST:event_cancelMouseEntered

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:

        aTypeShow.setText("");
        txtUser.setText("");
        txtPass.setText("");
        
        
        clk_passvisible.setVisible(false);
        
        txtUser.requestFocus();

    }//GEN-LAST:event_btnClearMouseClicked

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        // TODO add your handling code here:
        btnClear.setVisible(false);
    }//GEN-LAST:event_btnClearMouseExited

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_clearMouseExited

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        // TODO add your handling code here:
        btnClear.setVisible(true);
    }//GEN-LAST:event_clearMouseEntered

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        // TODO add your handling code here:

        
        if(aTypeShow.getText().length()==0){
            reqAcct.setVisible(true);
        } else{
            reqAcct.setVisible(false);
        }
        
        try
        {
            Encryption encrypt = new Encryption();
            String password = encrypt.SHA1(Arrays.toString(txtPass.getPassword()));
            
           /* Class.forName("org.apache.derby.jdbc.ClientDriver");
            String fidelString = "jdbc:derby://localhost:1527/UserLogin";
            Connection fidelcon = DriverManager.getConnection(fidelString, "login", "login");
            Statement fidelstmt = fidelcon.createStatement();
            String insertsql = "insert into users(uname, pword, access_type) values('"+txtUser.getText()+"', '"+password+"', '"+aTypeShow.getText()+"')";
            fidelstmt.execute(insertsql);
            fidelstmt.close();
            fidelcon.close();*/
           
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
            Connection con = DriverManager.getConnection(drive, "", "");
            Statement stmt = con.createStatement();
           
            String insertnew = "insert into users(uname,pword, access_type) values('"+txtUser.getText()+"','"+password+"', '"+aTypeShow.getText()+"')";
            stmt.execute(insertnew);
            stmt.close();
            con.close();
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, "New account saved!");
            

            txtUser.setText("");
            txtPass.setText("");
            aTypeShow.setText("");
            clk_passvisible.setVisible(false);
            passvisible.setVisible(false);
            txtUser.requestFocus();
            
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
        
        
        

    }//GEN-LAST:event_btnSubmitMouseClicked

    private void btnSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseExited
        // TODO add your handling code here:
        btnSubmit.setVisible(false);
    }//GEN-LAST:event_btnSubmitMouseExited

    private void submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_submitMouseExited

    private void submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseEntered
        // TODO add your handling code here:
        btnSubmit.setVisible(true);
    }//GEN-LAST:event_submitMouseEntered

    private void clk_passvisibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clk_passvisibleMouseClicked
        // TODO add your handling code here:
        passvisible.setVisible(true);
        clk_passvisible.setVisible(false);

        if(!clk_passvisible.isVisible()){
            txtPass.setEchoChar('*');
        }

    }//GEN-LAST:event_clk_passvisibleMouseClicked

    private void passvisibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passvisibleMouseClicked
        // TODO add your handling code here:
        passvisible.setVisible(false);
        clk_passvisible.setVisible(true);

        if (clk_passvisible.isVisible())
        {
            txtPass.setEchoChar((char)0);
        }

    }//GEN-LAST:event_passvisibleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newUserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aType0;
    private javax.swing.JLabel aType1;
    private javax.swing.JLabel aType2;
    private javax.swing.JLabel aType3;
    private javax.swing.JLabel aType4;
    private javax.swing.JLabel aTypeShow;
    private javax.swing.JLabel acct;
    private javax.swing.JPanel acctTypePanel;
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnSubmit;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel clear;
    private javax.swing.JLabel clk_passvisible;
    private javax.swing.JLabel form;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel passvisible;
    private javax.swing.JLabel rec;
    private javax.swing.JLabel reqAcct;
    private javax.swing.JLabel submit;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel user;
    private javax.swing.JLabel userTaken;
    // End of variables declaration//GEN-END:variables
}
