
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author johnrafaelrondilla
 */
public class searchPatientForm extends javax.swing.JFrame {

    /**
     * Creates new form searchPatientForm
     */
    public searchPatientForm() {
        initComponents();
        populateTable();
        btnsearchPatID.setVisible(false);
        btnClear.setVisible(false);
        btnCancel.setVisible(false);
        chkPatID.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblRecord = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();
        buttonsPanel2 = new javax.swing.JPanel();
        btnsearchPatID_disabled = new javax.swing.JLabel();
        btnsearchPatID = new javax.swing.JLabel();
        search2 = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        clear = new javax.swing.JLabel();
        txtPatID = new javax.swing.JTextField();
        patID = new javax.swing.JLabel();
        chkPatID = new javax.swing.JLabel();
        btnPatID = new javax.swing.JLabel();
        srchby = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buttonsPanel1 = new javax.swing.JPanel();
        btnCancel1 = new javax.swing.JLabel();
        cancel1 = new javax.swing.JLabel();
        btnClear1 = new javax.swing.JLabel();
        clear1 = new javax.swing.JLabel();
        btnSearch1 = new javax.swing.JLabel();
        search1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Procedure", "Remarks", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRecord.setEnabled(false);
        tblRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRecordMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblRecord);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 740, 210));

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Patient ID", "Name", "Date of Birth"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 740, 170));

        buttonsPanel2.setOpaque(false);
        buttonsPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsearchPatID_disabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchPatientForm/SEARCH-disabled.png"))); // NOI18N
        btnsearchPatID_disabled.setToolTipText("submit");
        btnsearchPatID_disabled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsearchPatID_disabledMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsearchPatID_disabledMouseExited(evt);
            }
        });
        buttonsPanel2.add(btnsearchPatID_disabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnsearchPatID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/buttons/SEARCH-HOV.png"))); // NOI18N
        btnsearchPatID.setToolTipText("submit");
        btnsearchPatID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsearchPatIDMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsearchPatIDMouseExited(evt);
            }
        });
        buttonsPanel2.add(btnsearchPatID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        search2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/buttons/SEARCH.png"))); // NOI18N
        search2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search2MouseEntered(evt);
            }
        });
        buttonsPanel2.add(search2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(buttonsPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 120, 60));

        buttonsPanel.setOpaque(false);
        buttonsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CANCEL-hover.png"))); // NOI18N
        btnCancel.setToolTipText("cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });
        buttonsPanel.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CANCEL.png"))); // NOI18N
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
        });
        buttonsPanel.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CLEAR-hover.png"))); // NOI18N
        btnClear.setToolTipText("clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });
        buttonsPanel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CLEAR.png"))); // NOI18N
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
        });
        buttonsPanel.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        getContentPane().add(buttonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 320, 60));

        txtPatID.setFont(new java.awt.Font("Helvetica", 2, 14)); // NOI18N
        txtPatID.setText("enter ID number");
        txtPatID.setBorder(null);
        txtPatID.setEnabled(false);
        txtPatID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPatIDFocusGained(evt);
            }
        });
        txtPatID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtPatID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 120, 30));

        patID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/box.png"))); // NOI18N
        getContentPane().add(patID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        chkPatID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/ckdDate.png"))); // NOI18N
        chkPatID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkPatIDMouseClicked(evt);
            }
        });
        getContentPane().add(chkPatID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 50));

        btnPatID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchPatientForm/Patient ID_.png"))); // NOI18N
        btnPatID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPatIDMouseClicked(evt);
            }
        });
        getContentPane().add(btnPatID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 50));

        srchby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/Search By_.png"))); // NOI18N
        getContentPane().add(srchby, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchPatientForm/SEARCH PATIENT RECORD.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchPatientForm/Layer 2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        buttonsPanel1.setOpaque(false);
        buttonsPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CANCEL-hover.png"))); // NOI18N
        btnCancel1.setToolTipText("cancel");
        btnCancel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancel1MouseExited(evt);
            }
        });
        buttonsPanel1.add(btnCancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        cancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CANCEL.png"))); // NOI18N
        cancel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancel1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancel1MouseEntered(evt);
            }
        });
        buttonsPanel1.add(cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        btnClear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CLEAR-hover.png"))); // NOI18N
        btnClear1.setToolTipText("clear");
        btnClear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClear1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClear1MouseExited(evt);
            }
        });
        buttonsPanel1.add(btnClear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        clear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CLEAR.png"))); // NOI18N
        clear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clear1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clear1MouseEntered(evt);
            }
        });
        buttonsPanel1.add(clear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        btnSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/buttons/SEARCH-HOV.png"))); // NOI18N
        btnSearch1.setToolTipText("submit");
        btnSearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearch1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearch1MouseExited(evt);
            }
        });
        buttonsPanel1.add(btnSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        search1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/buttons/SEARCH.png"))); // NOI18N
        search1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search1MouseEntered(evt);
            }
        });
        buttonsPanel1.add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(buttonsPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 310, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkPatIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkPatIDMouseClicked
        // TODO add your handling code here:
        chkPatID.setVisible(false);
        txtPatID.setEnabled(false);
        txtPatID.setText("enter ID number");
       
        btnsearchPatID_disabled.setVisible(true);
    }//GEN-LAST:event_chkPatIDMouseClicked

    private void btnPatIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPatIDMouseClicked
        populateTable();
        chkPatID.setVisible(true);
        txtPatID.setEnabled(true);

        txtPatID.setEnabled(true);
        
        btnsearchPatID_disabled.setVisible(false);
    }//GEN-LAST:event_btnPatIDMouseClicked

    private void txtPatIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPatIDFocusGained
        // TODO add your handling code here:
        txtPatID.setText("");
    }//GEN-LAST:event_txtPatIDFocusGained

    private void txtPatIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatIDActionPerformed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        mainForm m = new mainForm();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        // TODO add your handling code here:
        btnCancel.setVisible(false);
    }//GEN-LAST:event_btnCancelMouseExited

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseExited

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        // TODO add your handling code here:
        btnCancel.setVisible(true);
    }//GEN-LAST:event_cancelMouseEntered

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        txtPatID.setText("enter ID number");
        txtPatID.setEnabled(false);
        chkPatID.setVisible(false);
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        // TODO add your handling code here:
        btnClear.setVisible(false);
    }//GEN-LAST:event_btnClearMouseExited

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_clearMouseExited

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        // TODO add your handling code here:
        btnClear.setVisible(true);
    }//GEN-LAST:event_clearMouseEntered

    private void btnCancel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancel1MouseClicked

    private void btnCancel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancel1MouseExited

    private void cancel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cancel1MouseExited

    private void cancel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cancel1MouseEntered

    private void btnClear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClear1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear1MouseClicked

    private void btnClear1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClear1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear1MouseExited

    private void clear1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_clear1MouseExited

    private void clear1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_clear1MouseEntered

    private void btnSearch1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearch1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch1MouseClicked

    private void btnSearch1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearch1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch1MouseExited

    private void search1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_search1MouseExited

    private void search1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_search1MouseEntered

    private void btnsearchPatIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchPatIDMouseClicked
        // TODO add your handling code here:
        try
        {
            /*Class.forName("org.apache.derby.jdbc.ClientDriver");
            String fidelString = "jdbc:derby://localhost:1527/UserLogin";
            Connection fidelcon = DriverManager.getConnection(fidelString, "login", "login");
            Statement fidelstmt = fidelcon.createStatement();*/
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
            Connection con = DriverManager.getConnection(drive, "", "");
            Statement stmt = con.createStatement();
           
            ResultSet record;
            record = stmt.executeQuery("select procedures as Procedures, remarks as Remarks, date_ as Date_Performed from patientrecord where pID='"+txtPatID.getText()+"'");
            tblRecord.setModel(DbUtils.resultSetToTableModel(record));
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
    }//GEN-LAST:event_btnsearchPatIDMouseClicked

    private void btnsearchPatIDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchPatIDMouseExited
        // TODO add your handling code here:
        btnsearchPatID.setVisible(false);
    }//GEN-LAST:event_btnsearchPatIDMouseExited

    private void search2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_search2MouseExited

    private void search2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search2MouseEntered
        // TODO add your handling code here:
        btnsearchPatID.setVisible(true);
    }//GEN-LAST:event_search2MouseEntered

    private void btnsearchPatID_disabledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchPatID_disabledMouseClicked
        try
        {
            /*Class.forName("org.apache.derby.jdbc.ClientDriver");
            String fidelString = "jdbc:derby://localhost:1527/UserLogin";
            Connection fidelcon = DriverManager.getConnection(fidelString, "login", "login");
            Statement fidelstmt = fidelcon.createStatement();*/
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
            Connection con = DriverManager.getConnection(drive, "", "");
            Statement stmt = con.createStatement();
           
            ResultSet record;
            record = stmt.executeQuery("select procedures as Procedures, remarks as Remarks, date_ as Date_Performed from patientrecord where pID='"+txtPatID.getText()+"'");
            tblRecord.setModel(DbUtils.resultSetToTableModel(record));
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
    }//GEN-LAST:event_btnsearchPatID_disabledMouseClicked

    private void btnsearchPatID_disabledMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchPatID_disabledMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchPatID_disabledMouseExited

    private void tblInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInfoMouseClicked
        // TODO add your handling code here:
        int row = tblInfo.getSelectedRow();
        String id = (tblInfo.getModel().getValueAt(row, 0).toString());
        txtPatID.setText(id);
    }//GEN-LAST:event_tblInfoMouseClicked

    private void tblRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRecordMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblRecordMouseClicked

    public void populateTable()
    {
        try
        {
            /*
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            String fidelString = "jdbc:derby://localhost:1527/UserLogin";
            Connection fidelcon = DriverManager.getConnection(fidelString, "login", "login");
            Statement fidelstmt = fidelcon.createStatement();*/
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
            Connection con = DriverManager.getConnection(drive, "", "");
            Statement stmt = con.createStatement();
           
            ResultSet record;
            record = stmt.executeQuery("select pID as Patient_ID, pName as Patient_Name, pBirthdate as Date_of_Birth from patientinfo");
            tblInfo.setModel(DbUtils.resultSetToTableModel(record));
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchPatientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchPatientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnCancel1;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnClear1;
    private javax.swing.JLabel btnPatID;
    private javax.swing.JLabel btnSearch1;
    private javax.swing.JLabel btnsearchPatID;
    private javax.swing.JLabel btnsearchPatID_disabled;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JPanel buttonsPanel1;
    private javax.swing.JPanel buttonsPanel2;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel cancel1;
    private javax.swing.JLabel chkPatID;
    private javax.swing.JLabel clear;
    private javax.swing.JLabel clear1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel patID;
    private javax.swing.JLabel search1;
    private javax.swing.JLabel search2;
    private javax.swing.JLabel srchby;
    private javax.swing.JTable tblInfo;
    private javax.swing.JTable tblRecord;
    private javax.swing.JTextField txtPatID;
    // End of variables declaration//GEN-END:variables
}
