
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author johnrafaelrondilla
 */
public class servicesTallyForm extends javax.swing.JFrame {

    /**
     * Creates new form servicesTallyForm
     */
    public servicesTallyForm() {
        initComponents();
        
        btnClear.setVisible(false);
        btnSubmit.setVisible(false);
        btnCancel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblCount = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTally = new javax.swing.JTable();
        buttonsPanel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        clear = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JLabel();
        submit = new javax.swing.JLabel();
        txtProcName = new javax.swing.JTextField();
        fromDate2 = new javax.swing.JLabel();
        btnProcName = new javax.swing.JLabel();
        btnDate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFromDate = new javax.swing.JTextField();
        fromDate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtToDate = new javax.swing.JTextField();
        fromDate1 = new javax.swing.JLabel();
        srchby = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tblCount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Total"
            }
        ));
        jScrollPane2.setViewportView(tblCount);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 100, 50));

        tblTally.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Procedure", "Date Performed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTally);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 760, 300));

        buttonsPanel.setOpaque(false);
        buttonsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CANCEL-hover.png"))); // NOI18N
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });
        buttonsPanel.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CANCEL.png"))); // NOI18N
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
        });
        buttonsPanel.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CLEAR-hover.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });
        buttonsPanel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CLEAR.png"))); // NOI18N
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
        });
        buttonsPanel.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/buttons/SEARCH-HOV.png"))); // NOI18N
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubmitMouseExited(evt);
            }
        });
        buttonsPanel.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/buttons/SEARCH.png"))); // NOI18N
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitMouseExited(evt);
            }
        });
        buttonsPanel.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(buttonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 280, 50));

        txtProcName.setFont(new java.awt.Font("Helvetica", 2, 14)); // NOI18N
        txtProcName.setBorder(null);
        txtProcName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProcNameFocusGained(evt);
            }
        });
        getContentPane().add(txtProcName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 120, 30));

        fromDate2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/box.png"))); // NOI18N
        getContentPane().add(fromDate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        btnProcName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnProcName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servicesTally/Procedure Name_.png"))); // NOI18N
        btnProcName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProcNameMouseClicked(evt);
            }
        });
        getContentPane().add(btnProcName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, -1));

        btnDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/btnDate.png"))); // NOI18N
        btnDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDateMouseClicked(evt);
            }
        });
        getContentPane().add(btnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 40, 50));

        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("from:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 30));

        txtFromDate.setFont(new java.awt.Font("Helvetica", 2, 14)); // NOI18N
        txtFromDate.setText("yyyy-mm-dd");
        txtFromDate.setBorder(null);
        txtFromDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFromDateFocusGained(evt);
            }
        });
        getContentPane().add(txtFromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 120, 30));

        fromDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/box.png"))); // NOI18N
        getContentPane().add(fromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("to:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, 30));

        txtToDate.setFont(new java.awt.Font("Helvetica", 2, 14)); // NOI18N
        txtToDate.setText("yyyy-mm-dd");
        txtToDate.setBorder(null);
        txtToDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtToDateFocusGained(evt);
            }
        });
        getContentPane().add(txtToDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 120, 30));

        fromDate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/box.png"))); // NOI18N
        getContentPane().add(fromDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        srchby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginHistoryForm/Search By_.png"))); // NOI18N
        getContentPane().add(srchby, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servicesTally/SERVICES TALLY.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/servicesTally/Layer 2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDateMouseClicked
        // TODO add your handling code here:
        txtFromDate.setEnabled(true);

        txtToDate.setEnabled(true);

        txtProcName.setEnabled(false);
        txtProcName.setText("enter procedure...");
    }//GEN-LAST:event_btnDateMouseClicked

    private void txtFromDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFromDateFocusGained
        // TODO add your handling code here:
        txtFromDate.setText("");
    }//GEN-LAST:event_txtFromDateFocusGained

    private void txtToDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtToDateFocusGained
        // TODO add your handling code here:
        txtToDate.setText("");
    }//GEN-LAST:event_txtToDateFocusGained

    private void txtProcNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProcNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProcNameFocusGained

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        mainForm m = new mainForm();
        m.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        // TODO add your handling code here:
        btnCancel.setVisible(false);
    }//GEN-LAST:event_btnCancelMouseExited

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseExited

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        // TODO add your handling code here:
        btnCancel.setVisible(true);
    }//GEN-LAST:event_cancelMouseEntered

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        txtFromDate.setEnabled(false);
        txtToDate.setEnabled(false);
        txtProcName.setEnabled(false);
        txtFromDate.setText("yyyy-mm-dd");
        txtToDate.setText("yyyy-mm-dd");
        txtProcName.setText("enter procedure...");
        txtFromDate.requestFocus();

    }//GEN-LAST:event_btnClearMouseClicked

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        // TODO add your handling code here:
        btnClear.setVisible(false);
    }//GEN-LAST:event_btnClearMouseExited

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_clearMouseExited

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        // TODO add your handling code here:
        btnClear.setVisible(true);
    }//GEN-LAST:event_clearMouseEntered

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked

        
        if(txtFromDate.getText().equals("") || txtToDate.getText().equals("") || txtProcName.getText().equals("") || txtFromDate.getText().equals("yyyy-mm-dd") || txtToDate.getText().equals("yyyy-mm-dd") || txtProcName.getText().equals("type procedure here..."))
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, "Please enter values on the given field.");
        }
        else
        {
            try
            {
                /*Class.forName("org.apache.derby.jdbc.ClientDriver");
                String fidelString = "jdbc:derby://localhost:1527/UserLogin";
                Connection fidelcon = DriverManager.getConnection(fidelString, "login", "login");
                Statement fidelstmt = fidelcon.createStatement();*/
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
                Connection con = DriverManager.getConnection(drive, "", "");
                Statement stmt = con.createStatement();
                ResultSet record1;
                record1 = stmt.executeQuery("select procedures, date_ from patientrecord where procedures like '%"+txtProcName.getText()+"%' and date_ between '"+txtFromDate.getText()+"' and '"+txtToDate.getText()+"'");
                tblTally.setModel(DbUtils.resultSetToTableModel(record1));
                stmt.close();
                con.close();
            }
            catch(Exception e)
            {
                JFrame frame = new JFrame();
                frame.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(frame, e.getMessage());
            }
            
            try
            {
               /* Class.forName("org.apache.derby.jdbc.ClientDriver");
                String fidelString = "jdbc:derby://localhost:1527/UserLogin";
                Connection fidelcon1 = DriverManager.getConnection(fidelString, "login", "login");
                Statement fidelstmt1 = fidelcon1.createStatement();*/
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
                Connection con1 = DriverManager.getConnection(drive, "", "");
                Statement stmt1 = con1.createStatement();
                ResultSet record2;
                record2 = stmt1.executeQuery("select count(procedures) as Total from patientrecord where procedures like '%"+txtProcName.getText()+"%' and date_ between '"+txtFromDate.getText()+"' and '"+txtToDate.getText()+"'");
                tblCount.setModel(DbUtils.resultSetToTableModel(record2));
                stmt1.close();
                con1.close();
            }
            catch(Exception e)
            {
                JFrame frame = new JFrame();
                frame.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(frame, e.getMessage());
            }
        }

    }//GEN-LAST:event_btnSubmitMouseClicked

    private void btnSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseExited
        // TODO add your handling code here:
        btnSubmit.setVisible(false);
    }//GEN-LAST:event_btnSubmitMouseExited

    private void submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_submitMouseExited

    private void submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseEntered
        // TODO add your handling code here:
        btnSubmit.setVisible(true);
    }//GEN-LAST:event_submitMouseEntered

    private void btnProcNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProcNameMouseClicked
        // TODO add your handling code here:
        
        txtFromDate.setEnabled(false);
        txtFromDate.setText("yyyy-mm-dd");
        txtToDate.setText("yyyy-mm-dd");
        txtToDate.setEnabled(false);
        
        txtProcName.setEnabled(true);
        
    }//GEN-LAST:event_btnProcNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(servicesTallyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(servicesTallyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(servicesTallyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(servicesTallyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new servicesTallyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnDate;
    private javax.swing.JLabel btnProcName;
    private javax.swing.JLabel btnSubmit;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel clear;
    private javax.swing.JLabel fromDate;
    private javax.swing.JLabel fromDate1;
    private javax.swing.JLabel fromDate2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel srchby;
    private javax.swing.JLabel submit;
    private javax.swing.JTable tblCount;
    private javax.swing.JTable tblTally;
    private javax.swing.JTextField txtFromDate;
    private javax.swing.JTextField txtProcName;
    private javax.swing.JTextField txtToDate;
    // End of variables declaration//GEN-END:variables
}
