
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author johnrafaelrondilla
 */
public class updateUserForm extends javax.swing.JFrame {

    /**
     * Creates new form updateUserForm
     */
    public updateUserForm() {
        initComponents();
        populateTable();
        acctTypePanel.setVisible(false);
        btnUpdate.setVisible(false);
        btnClear.setVisible(false);
        btnCancel.setVisible(false);
        txtUser.setVisible(false);
        txtPass.setVisible(false);
        lblAcct.setVisible(false);
        aType3.setVisible(false);
        aType4.setVisible(false);
        txtUser.setText(userLog.ase);
        txtUser.setBackground(new Color(0,0,0,0));
        txtPass.setBackground(new Color(0,0,0,0));
        lblAcct.setBackground(new Color(0,0,0,0));
        updateDisabled.setVisible(false);
        clearDisabled.setVisible(false);
        acctTypePanel.setVisible(true);
        txtUser.setVisible(true);
        txtPass.setVisible(true);
        lblAcct.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAcct = new javax.swing.JLabel();
        acctTypePanel = new javax.swing.JPanel();
        aType4 = new javax.swing.JLabel();
        aType3 = new javax.swing.JLabel();
        aType2 = new javax.swing.JLabel();
        aType1 = new javax.swing.JLabel();
        aType0 = new javax.swing.JLabel();
        updateUserPane = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        buttonsPanel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        clearDisabled = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        clear = new javax.swing.JLabel();
        updateDisabled = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JLabel();
        update = new javax.swing.JLabel();
        form = new javax.swing.JPanel();
        txtPass = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        acctDisabled = new javax.swing.JLabel();
        passDisabled = new javax.swing.JLabel();
        userDisabled = new javax.swing.JLabel();
        userEnabled = new javax.swing.JLabel();
        acctEnabled = new javax.swing.JLabel();
        passEnabled = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAcct.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblAcct.setText("lblAcct");
        getContentPane().add(lblAcct, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 210, 50));

        acctTypePanel.setMaximumSize(new java.awt.Dimension(188, 147));
        acctTypePanel.setMinimumSize(new java.awt.Dimension(188, 147));
        acctTypePanel.setOpaque(false);
        acctTypePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aType4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createNewUserForm/accttype/Assistant-hov.png"))); // NOI18N
        aType4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aType4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aType4MouseExited(evt);
            }
        });
        acctTypePanel.add(aType4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        aType3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createNewUserForm/accttype/Dentist-hov.png"))); // NOI18N
        aType3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aType3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aType3MouseExited(evt);
            }
        });
        acctTypePanel.add(aType3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        aType2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createNewUserForm/accttype/Assistant.png"))); // NOI18N
        aType2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aType2MouseEntered(evt);
            }
        });
        acctTypePanel.add(aType2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, -1));

        aType1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createNewUserForm/accttype/Dentist.png"))); // NOI18N
        aType1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aType1MouseEntered(evt);
            }
        });
        acctTypePanel.add(aType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, -1));

        aType0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/createNewUserForm/accttype/accttype_click.png"))); // NOI18N
        aType0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aType0MouseClicked(evt);
            }
        });
        acctTypePanel.add(aType0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        getContentPane().add(acctTypePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 190, 160));

        updateUserPane.setBorder(null);
        updateUserPane.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N

        tblUsers.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Password", "Account Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsers.setOpaque(false);
        tblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsersMouseClicked(evt);
            }
        });
        updateUserPane.setViewportView(tblUsers);

        getContentPane().add(updateUserPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 750, 310));

        buttonsPanel.setOpaque(false);
        buttonsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CANCEL-hover.png"))); // NOI18N
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });
        buttonsPanel.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CANCEL.png"))); // NOI18N
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
        });
        buttonsPanel.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        clearDisabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/updateBtn/CLEAR-disabled.png"))); // NOI18N
        clearDisabled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearDisabledMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearDisabledMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearDisabledMouseExited(evt);
            }
        });
        buttonsPanel.add(clearDisabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CLEAR-hover.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });
        buttonsPanel.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dentalInfo/buttons-hover/CLEAR.png"))); // NOI18N
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
        });
        buttonsPanel.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        updateDisabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/updateBtn/update-disabled.png"))); // NOI18N
        updateDisabled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateDisabledMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateDisabledMouseExited(evt);
            }
        });
        buttonsPanel.add(updateDisabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/updateBtn/SEARCH1-HOV.png"))); // NOI18N
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });
        buttonsPanel.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/updateBtn/SEARCH.png"))); // NOI18N
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
        });
        buttonsPanel.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(buttonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 280, 50));

        form.setMaximumSize(new java.awt.Dimension(800, 600));
        form.setMinimumSize(new java.awt.Dimension(800, 600));
        form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(form, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtPass.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        txtPass.setToolTipText("enter password");
        txtPass.setBorder(null);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 170, 30));

        txtUser.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        txtUser.setToolTipText("enter last name");
        txtUser.setBorder(null);
        txtUser.setEnabled(false);
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 170, 30));

        acctDisabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/acctType-disabled.png"))); // NOI18N
        getContentPane().add(acctDisabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        passDisabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/pass-disabled.png"))); // NOI18N
        getContentPane().add(passDisabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        userDisabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/user-disabled.png"))); // NOI18N
        getContentPane().add(userDisabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        userEnabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/user-enabled.png"))); // NOI18N
        getContentPane().add(userEnabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        acctEnabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/acctType-enabled.png"))); // NOI18N
        getContentPane().add(acctEnabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        passEnabled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/pass-enabled.png"))); // NOI18N
        getContentPane().add(passEnabled, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/UPDATE USER.png"))); // NOI18N
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateUserForm/Layer 1.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 280));

        setSize(new java.awt.Dimension(464, 306));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        mainForm m = new mainForm();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        // TODO add your handling code here:
        btnCancel.setVisible(false);
    }//GEN-LAST:event_btnCancelMouseExited

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseExited

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        // TODO add your handling code here:
        btnCancel.setVisible(true);
    }//GEN-LAST:event_cancelMouseEntered

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        txtUser.setText("");
        txtPass.setText("");
        lblAcct.setText("");
        
        userDisabled.setVisible(true);
        passDisabled.setVisible(true);
        acctDisabled.setVisible(true);
        updateDisabled.setVisible(true);
        clearDisabled.setVisible(true);
        acctTypePanel.setVisible(false);
        aType3.setVisible(false);
        aType4.setVisible(false);
        

    }//GEN-LAST:event_btnClearMouseClicked

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        // TODO add your handling code here:
        btnClear.setVisible(false);
    }//GEN-LAST:event_btnClearMouseExited

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_clearMouseExited

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        // TODO add your handling code here:
        btnClear.setVisible(true);
    }//GEN-LAST:event_clearMouseEntered

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        
        
        //enter database here
        
        try
        {
            Encryption encrypt = new Encryption();
            String password = encrypt.SHA1(Arrays.toString(txtPass.getPassword()));
            
            /*Class.forName("org.apache.derby.jdbc.ClientDriver");
            String fidelString = "jdbc:derby://localhost:1527/UserLogin";
            Connection fidelcon = DriverManager.getConnection(fidelString, "login", "login");
            Statement fidelstmt = fidelcon.createStatement();*/
            
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
            Connection con = DriverManager.getConnection(drive, "", "");
            Statement stmt = con.createStatement();
            
            String insertsql = "update users set uname='"+txtUser.getText()+"', pword='"+password+"', access_type='"+lblAcct.getText()+"' where uname='"+txtUser.getText()+"'";
            stmt.execute(insertsql);
            stmt.close();
            con.close();
            
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, "Account updated.");
            
            //txtUser.setText("");
            txtPass.setText("");
            acctTypePanel.setVisible(false);
            lblAcct.setText("");
            
            userDisabled.setVisible(true);
            passDisabled.setVisible(true);
            acctDisabled.setVisible(true);
            
            updateDisabled.setVisible(true);
            clearDisabled.setVisible(true);

            
            populateTable();
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
        

    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        // TODO add your handling code here:
        btnUpdate.setVisible(false);
    }//GEN-LAST:event_btnUpdateMouseExited

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_updateMouseExited

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        // TODO add your handling code here:
        btnUpdate.setVisible(true);
    }//GEN-LAST:event_updateMouseEntered

    private void updateDisabledMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateDisabledMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_updateDisabledMouseExited

    private void updateDisabledMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateDisabledMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_updateDisabledMouseEntered

    private void clearDisabledMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearDisabledMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_clearDisabledMouseExited

    private void clearDisabledMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearDisabledMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_clearDisabledMouseEntered

    private void aType4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aType4MouseClicked
        // TODO add your handling code here:
        lblAcct.setText("user");
        acctTypePanel.setVisible(false);

        

    }//GEN-LAST:event_aType4MouseClicked

    private void aType4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aType4MouseExited
        // TODO add your handling code here:
        aType4.setVisible(false);
    }//GEN-LAST:event_aType4MouseExited

    private void aType3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aType3MouseClicked
        // TODO add your handling code here:
        lblAcct.setText("admin");
        acctTypePanel.setVisible(false);

        

    }//GEN-LAST:event_aType3MouseClicked

    private void aType3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aType3MouseExited
        // TODO add your handling code here:
        aType3.setVisible(false);
    }//GEN-LAST:event_aType3MouseExited

    private void aType2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aType2MouseEntered
        // TODO add your handling code here:
        aType4.setVisible(true);
    }//GEN-LAST:event_aType2MouseEntered

    private void aType1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aType1MouseEntered
        // TODO add your handling code here:
        aType3.setVisible(true);
    }//GEN-LAST:event_aType1MouseEntered

    private void aType0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aType0MouseClicked
        // TODO add your handling code here:
        acctTypePanel.setVisible(false);
    }//GEN-LAST:event_aType0MouseClicked

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void tblUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsersMouseClicked
        // TODO add your handling code here:
        updateDisabled.setVisible(false);
        clearDisabled.setVisible(false);
        acctTypePanel.setVisible(true);
        txtUser.setVisible(true);
        txtPass.setVisible(true);
        lblAcct.setVisible(true);
        
        
        int row = tblUsers.getSelectedRow();
        String username = (tblUsers.getModel().getValueAt(row, 0).toString());
        try
        {
            /*Class.forName("org.apache.derby.jdbc.ClientDriver");
            String fidelString = "jdbc:derby://localhost:1527/UserLogin";
            Connection fidelcon = DriverManager.getConnection(fidelString, "login", "login");
            Statement fidelstmt = fidelcon.createStatement();*/
            
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
            Connection con = DriverManager.getConnection(drive, "", "");
            Statement stmt = con.createStatement();
            
            String query = "select * from users where uname='"+username+"'";
            ResultSet result = stmt.executeQuery(query);
            
            if(result.next())
            {
                String field1 = result.getString("uname");
                txtUser.setText(field1);
                String field2 = result.getString("pword");
                txtPass.setText(field2);
                String field3 = result.getString("access_type");
                lblAcct.setText(field3);
                
            }
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
    }                                              

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {                                              
        txtUser.setText("");
        txtPass.setText("");
        lblAcct.setText("");
        
        userDisabled.setVisible(true);
        passDisabled.setVisible(true);
        acctDisabled.setVisible(true);
        updateDisabled.setVisible(true);
        clearDisabled.setVisible(true);
        
        
    }//GEN-LAST:event_tblUsersMouseClicked

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void clearDisabledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearDisabledMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clearDisabledMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateUserForm().setVisible(true);
            }
        });
    }
    
    public void populateTable()
    {
        try
        {
            /*Class.forName("org.apache.derby.jdbc.ClientDriver");
            String fidelString = "jdbc:derby://localhost:1527/UserLogin";
            Connection fidelcon = DriverManager.getConnection(fidelString, "login", "login");
            Statement fidelstmt = fidelcon.createStatement();
            ResultSet fidelrecord;*/
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String drive = "jdbc:ucanaccess://Clinic Database.mdb;";
            Connection con = DriverManager.getConnection(drive, "", "");
            Statement stmt = con.createStatement();
            ResultSet record;
            
            record = stmt.executeQuery("select uname as Username, access_type as Access from users");
            tblUsers.setModel(DbUtils.resultSetToTableModel(record));
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(frame, e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aType0;
    private javax.swing.JLabel aType1;
    private javax.swing.JLabel aType2;
    private javax.swing.JLabel aType3;
    private javax.swing.JLabel aType4;
    private javax.swing.JLabel acctDisabled;
    private javax.swing.JLabel acctEnabled;
    private javax.swing.JPanel acctTypePanel;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel clear;
    private javax.swing.JLabel clearDisabled;
    private javax.swing.JPanel form;
    private javax.swing.JLabel lblAcct;
    private javax.swing.JLabel passDisabled;
    private javax.swing.JLabel passEnabled;
    private javax.swing.JTable tblUsers;
    private javax.swing.JLabel title;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel update;
    private javax.swing.JLabel updateDisabled;
    private javax.swing.JScrollPane updateUserPane;
    private javax.swing.JLabel userDisabled;
    private javax.swing.JLabel userEnabled;
    // End of variables declaration//GEN-END:variables
}
